apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.17.4
    chart: victoria-metrics-k8s-stack
    helm:
      releaseName: vm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true